### PR TITLE
Hsla pr

### PR DESCRIPTION
**Pull request by outofambit**
Some ideas for giving the coder a little control over the randomness of colors. What do you think?

### CODE REVIEW

**Comment by mknadler** [comment]
@nickmasso: these look great! Thanks! Smart implementations.

I have a few questions:
1. Why does random-color-by-hue have a default? Why is that default 270?
2. Why does random-color-by-hue clamp saturation and lightness between 20 and 80, specifically? Why not 0 and 100? Granted, you'd end up with more 'boring' colors, but, random, nu? Perhaps this should be an optional parameter?

**Comment by outofambit** [comment]
@mknadler Thank you! Here's my responses to your two questions.
1. I guess I was thinking that if someone was really not wanting to think too much about the color they wanted, they could just have a shade of blue (though looking now I think I may have gotten the degree wrong for blue). Do you think it would make more sense to not have a default? That seems fine to me.
2. I picked 20 and 80 somewhat arbitrarily, but yes the intent was to prevent the user from getting grayscale colors much of the time. Could you say more about your idea for an optional parameter? Like an extra boolean for eliminating grayscale colors? What if there was another function called random-gray()?

**Comment by mknadler** [comment]
@nickmasso 
1. 270 seems to be a lovely purple, actually. I'm thinking a default hue is unnecessary here, as, after all, randomizing _by hue_ is the main purpose of the function.
2. A boolean could actually be a good solution for this; for now, I think perhaps saturation, especially, should have it's maximum default value upped to 100. Another solution, I'm thinking, would be to allow the user to just manually pass in their own saturation and lightness modifiers; something like `background: random-color-by-hue(120, 0 through 90, 20 through 85, 1)`, or `background: random-color-by-hue(120, 0, 90, 20, 85, 1)`,  for instance. 

I made this pen to demonstrate the difference between a max saturation of 80 and 100; missing out on some more vivid colors with it capped at 80:
http://codepen.io/mknadler/pen/b26ec34221f79a631b08373544c27f93

What I'm planning on doing, if you're cool with it, is merging your work as-is, and then subsequently changing:
A. The default `$hue: 270` to a non-default parameter;
B. The `random-between(20, 80)` saturation default to, for now, `random-between(20, 100)`
C. Adding saturation and lightness parameters to `random-color-by-hue`

Sound good?

**Comment by outofambit** [comment]
Sounds great!

You're totally right about the saturation cap. My mistake. And I didn't know you could use `through` like that. Really cool.

**Comment by mknadler** [comment]
Not manually, you can't!
From `sass -i`:

> > $test: 20 through 30
> > (20 "through" 30)
> > type-of($test)
> > "list"
> > nth($test, 1)
> > 20
> > nth($test, 2)
> > "through"

so, it'd be a list. If that is the syntax that ends up being used (straight up numbers might be more consistent with the rest of the library, though), I'd have the function check to see if a list was passed through, check to see if the second value in that list was a string, parse that list into numbers, and then feed those numbers into random-between.

**Pull request merged**
